# polar-container-lib/nix/entrypoint.nix
#
# Generates the container entrypoint script (start.nu) from a translated
# ContainerConfig. Only invoked for non-minimal containers — minimal containers
# exec their entrypoint or shell binary directly, no start.nu involved.
#
# Phase order:
#   1.  Helpers
#   2.  Store-path exports
#   3.  User creation        (cfg.user.createUser)
#   4.  AI setup             (cfg.ai.enable)
#   5.  Sudo setup           (cfg.user.supplementalGroups != [])
#   6.  Arch config          (cfg.nix.enableDaemon)
#   7.  Nix daemon           (cfg.nix.enableDaemon)
#   8.  SFTP symlink         (cfg.ssh != null)
#   9.  Cargo cache          (cfg.hasToolchain)
#  10.  Banner
#  11.  Write vigil layer + launch
#       - ci/pipeline: vigild as PID 1, pipeline-runner supervised
#       - dev/agent:   vigild backgrounded, shell exec'd as foreground

{ pkgs
, cfg
, devEnv
, inputs ? {}
}:

let
  lib = pkgs.lib;

  shellBin =
    if cfg.shell != null
    then cfg.shell.shell
    else "/bin/nu";

  nuBin = "${pkgs.nushell}/bin/nu";

  # ---------------------------------------------------------------------------
  # Phase 1: Preamble + helpers
  # ---------------------------------------------------------------------------
  phasePreamble = ''
    #!/usr/bin/env nu
    # start.nu — container entrypoint (generated by nix-container-lib)

    def die [msg: string] {
        print --stderr $"error: ($msg)"
        exit 1
    }

    def need [bin: string] {
        if (which $bin | is-empty) {
            die $"missing binary: ($bin)"
        }
    }

    def warn [msg: string] {
        print --stderr $"warning: ($msg)"
    }

    def file-append [path: string, content: string] {
        $content | save --append $path
    }

    def passwd-update [username: string, uid: int, gid: int, home: string, shell: string] {
        open --raw /etc/passwd
        | lines
        | each { |line|
            if ($line | str starts-with $"($username):") {
                $"($username):x:($uid):($gid)::($home):($shell)"
            } else {
                $line
            }
        }
        | str join "\n"
        | $"($in)\n"
        | save --force /etc/passwd
    }

    def group-add-member [groupname: string, member: string] {
        open --raw /etc/group
        | lines
        | each { |line|
            if ($line | str starts-with $"($groupname):") {
                let trailing = ($line | split row ":" | last)
                if ($trailing | is-empty) {
                    $"($line)($member)"
                } else {
                    $"($line),($member)"
                }
            } else {
                $line
            }
        }
        | str join "\n"
        | $"($in)\n"
        | save --force /etc/group
    }

  '';

  # ---------------------------------------------------------------------------
  # Phase 2: Store-path exports
  # ---------------------------------------------------------------------------
  phaseStorePathExports =
    let
      builtinExports = ''
        ##############################################################################
        # Store-path exports (arch-correct — evaluated in target derivation context)
        ##############################################################################
        $env.LOCALE_ARCHIVE      = "${pkgs.glibcLocalesUtf8}/lib/locale/locale-archive"
        $env.COREUTILS = "${inputs.uutils-micro.packages.${pkgs.system}.default or pkgs.uutils-coreutils-noprefix}"
        $env.OPENSSL_DIR         = "${pkgs.openssl.dev}"
        $env.OPENSSL_LIB_DIR     = "${pkgs.openssl.out}/lib"
        $env.OPENSSL_INCLUDE_DIR = "${pkgs.openssl.dev}/include"
        $env.PKG_CONFIG_PATH     = $"${pkgs.openssl.dev}/lib/pkgconfig:(if ($env.PKG_CONFIG_PATH? | default '''''' | is-empty) { '''''' } else { $'''''':($env.PKG_CONFIG_PATH)'''''' })"
      '' + lib.optionalString (cfg.shell != null && cfg.shell.type == "interactive-fish") ''
        $env.BOB_THE_FISH = "${pkgs.fishPlugins.bobthefish}"
        $env.FISH_BASS    = "${pkgs.fishPlugins.bass}"
        $env.FISH_GRC     = "${pkgs.fishPlugins.grc}"
      '' + lib.optionalString cfg.hasToolchain ''
        $env.LIBCLANG_PATH = "${pkgs.llvmPackages_19.libclang.lib}/lib"
      '';
      userExports = lib.concatMapStrings
        (ev: "$env.${ev.name} = ${lib.escapeShellArg ev.value}\n")
        cfg.startTimeEnv;
    in
      builtinExports + userExports;

  # ---------------------------------------------------------------------------
  # Phase 3: User creation
  # ---------------------------------------------------------------------------
  phaseUserCreation =
    if cfg.user.createUser
    then ''
      ##############################################################################
      # User creation
      ##############################################################################
      def create-user [username: string, uid: int, gid: int] {
          passwd-update $username $uid $gid $"/home/($username)" "${shellBin}"

          file-append /etc/shadow $"($username):!x:::::::\n"

          ^mkdir -p $"/home/($username)"
          ^chmod -R 755 $"/home/($username)"
          ^chown -R $"($uid):($gid)" $"/home/($username)"

          for dir in [".config" ".local/share" ".cache" ".ssh"] {
              ^install -d -m 700 $"/home/($username)/($dir)"
          }
          ^chown $"($uid):($gid)" $"/home/($username)/.config"
          ^chown $"($uid):($gid)" $"/home/($username)/.local/share"
          ^chown $"($uid):($gid)" $"/home/($username)/.cache"
          ^chown $"($uid):($gid)" $"/home/($username)/.ssh"

          need rsync
          if ("/root" | path exists) {
              ^rsync -a $"--chown=($uid):($gid)" /root/ $"/home/($username)/" | ignore
          }

          ^chmod 1777 /tmp

          ${if shellBin == "/bin/nu" then ''
          ^install -Dm644 "${cfg.user.skeletonPath}/config.nu" $"/home/($username)/.config/nushell/config.nu"
          ^install -Dm644 "${cfg.user.skeletonPath}/env.nu"    $"/home/($username)/.config/nushell/env.nu"
          if ("/etc/nushell/plugin-registry.msgpackz" | path exists) {
              ^install -Dm644 /etc/nushell/plugin-registry.msgpackz $"/home/($username)/.config/nushell/plugin.msgpackz"
          }
          '' else ''
          ^install -Dm644 "${cfg.user.skeletonPath}/config.fish" $"/home/($username)/.config/fish/config.fish"
          ^touch $"/home/($username)/.config/fish/fish_variables"
          ''}

          ^chown -R $"($uid):($gid)" $"/home/($username)"
          ^chmod -R 755 $"/home/($username)"
          ^chmod u+w $"/home/($username)"

          ${let suppGroups = builtins.concatStringsSep ","
              (map (g: "${g.name}:${toString g.gid}") cfg.user.supplementalGroups);
            in lib.optionalString (suppGroups != "") ''
          let supp_groups = "${suppGroups}"
          if not ($supp_groups | is-empty) {
              $supp_groups | split row "," | each { |entry|
                  let g_name = ($entry | split row ":" | first)
                  let g_gid  = ($entry | split row ":" | last | into int)
                  let exists = (open --raw /etc/group | lines | any { str starts-with $"($g_name):" })
                  if $exists {
                      group-add-member $g_name $username
                  } else {
                      file-append /etc/group   $"($g_name):x:($g_gid):($username)\n"
                      file-append /etc/gshadow $"($g_name):!::\n"
                  }
              }
          }
          ''}
      }

      # Attempt user creation — degrade gracefully if env vars missing
      let user_vars_set = ((not ($env.CREATE_USER? | default "" | is-empty)) and
                           (not ($env.CREATE_UID?  | default "" | is-empty)) and
                           (not ($env.CREATE_GID?  | default "" | is-empty)))

      if $user_vars_set {
          create-user $env.CREATE_USER ($env.CREATE_UID | into int) ($env.CREATE_GID | into int)
      } else {
          warn "CREATE_USER/CREATE_UID/CREATE_GID not set — running as root"
          warn "To create a user, pass: -e CREATE_USER=name -e CREATE_UID=1000 -e CREATE_GID=1000"
      }

      let dev_user = if $user_vars_set {
          { user: $env.CREATE_USER, uid: ($env.CREATE_UID | into int), gid: ($env.CREATE_GID | into int) }
      } else {
          { user: "root", uid: 0, gid: 0 }
      }
    ''
    else ''
      let dev_user = { user: "root", uid: 0, gid: 0 }
    '';

  # ---------------------------------------------------------------------------
  # Phase 4: AI setup
  # ---------------------------------------------------------------------------
  phaseAiSetup =
    if cfg.ai.enable or false
    then ''
      ##############################################################################
      # AI tooling setup
      ##############################################################################
      if ("/opt/llama-models" | path exists) {
          ^mkdir -p $"/home/($dev_user.user)/.cache/huggingface"
          ^ln -sfn /opt/llama-models $"/home/($dev_user.user)/.cache/llama.cpp"
          ^ln -sfn /opt/llama-models $"/home/($dev_user.user)/.cache/huggingface/hub"
          ^chown -h $"($dev_user.uid):($dev_user.gid)" $"/home/($dev_user.user)/.cache/llama.cpp"
          ^chown -h $"($dev_user.uid):($dev_user.gid)" $"/home/($dev_user.user)/.cache/huggingface/hub"
      }
      if ("/opt/ollama" | path exists) {
          ^ln -sfn /opt/ollama $"/home/($dev_user.user)/.ollama"
          ^chown -h $"($dev_user.uid):($dev_user.gid)" $"/home/($dev_user.user)/.ollama"
      }
      if ("/opt/pi" | path exists) {
          ^ln -sfn /opt/pi $"/home/($dev_user.user)/.pi"
          ^chown -h $"($dev_user.uid):($dev_user.gid)" $"/home/($dev_user.user)/.pi"
      }
      if (which ollama | is-not-empty) {
          let ollama_bin = (which ollama | get path | first)
          let ollama_lib = ($ollama_bin | path dirname | path join "../lib/ollama")
          if ($ollama_lib | path exists) {
              $env.LD_LIBRARY_PATH = $"($ollama_lib):(if ($env.LD_LIBRARY_PATH? | default '''''' | is-empty) { '''''' } else { $'''''':($env.LD_LIBRARY_PATH)'''''' })"
          }
      }
      if ("/run/opengl-driver/lib" | path exists) {
          $env.LD_LIBRARY_PATH = $"/run/opengl-driver/lib:(if ($env.LD_LIBRARY_PATH? | default '''''' | is-empty) { '''''' } else { $'''''':($env.LD_LIBRARY_PATH)'''''' })"
      }
    ''
    else "";

  # ---------------------------------------------------------------------------
  # Phase 5: Sudo setup
  # ---------------------------------------------------------------------------
  phaseSudo =
    if cfg.user.supplementalGroups != []
    then ''
      ##############################################################################
      # Sudo setup
      ##############################################################################
      let sudo_real = (
          do { ^readlink -f /bin/sudo } | complete
          | if $in.exit_code == 0 { $in.stdout | str trim } else { "" }
      )
      if not ($sudo_real | is-empty) {
          ^cp $sudo_real /usr/bin/sudo
          ^chown root:root /usr/bin/sudo
          ^chmod 4755 /usr/bin/sudo
          if not ("/etc/sudoers" | path exists) {
              "root ALL=(ALL:ALL) ALL\n#includedir /etc/sudoers.d\n" | save /etc/sudoers
              ^chmod 440 /etc/sudoers
          }
          ^mkdir -p /etc/sudoers.d
          let llama_bin = (which llama-server | get path? | first? | default "")
          if not ($llama_bin | is-empty) {
              $"($dev_user.user) ALL=(root) NOPASSWD: ($llama_bin)\n" | save /etc/sudoers.d/llama-server
              ^chmod 440 /etc/sudoers.d/llama-server
          }
          ^mkdir -p /etc/pam.d
          [ "auth       sufficient   pam_permit.so"
            "account    sufficient   pam_permit.so"
            "session    sufficient   pam_permit.so" ]
          | str join "\n"
          | $"($in)\n"
          | save /etc/pam.d/sudo
      }
    ''
    else "";

  # ---------------------------------------------------------------------------
  # Phase 6+7: Arch config + Nix daemon
  # ---------------------------------------------------------------------------
  phaseNixDaemon =
    if cfg.nix.enableDaemon
    then
      let
        buildUserBlock =
          if cfg.nix.buildUserCount.dynamic
          then "let cpus = (^nproc | str trim | into int)"
          else "let cpus = ${toString cfg.nix.buildUserCount.fixed}";
        sandboxBlock =
          if cfg.nix.sandboxPolicy == "enabled" then
            ''file-append /etc/nix/nix.conf "\nsandbox = true\n"''
          else if cfg.nix.sandboxPolicy == "disabled" then
            ''file-append /etc/nix/nix.conf "\nsandbox = false\n"''
          else ''
            let cpu_impl = (open --raw /proc/cpuinfo | lines | where { str contains "CPU implementer" } | first? | default "" | split row ":" | last | str trim)
            if $cpu_impl == "0x00" {
                file-append /etc/nix/nix.conf "\nsandbox = false\nfilter-syscalls = false\n"
            }
          '';
      in ''
        ##############################################################################
        # Nix daemon setup
        ##############################################################################
        file-append /etc/nix/nix.conf $"\nextra-trusted-users = ($dev_user.user)\n"

        ${buildUserBlock}

        file-append /etc/group   "nixbld:x:30000:\n"
        file-append /etc/gshadow "nixbld:x::\n"
        ^mkdir -p /var/empty

        let dummy_shell = if ("/bin/nologin" | path exists) { "/bin/nologin" } else { "/bin/false" }

        let members = (seq 1 $cpus | each { |i|
            let muid  = 30000 + $i
            let mname = $"nixbld($i)"
            let exists = (open --raw /etc/passwd | lines | any { str starts-with $"($mname):" })
            if not $exists {
                file-append /etc/passwd $"($mname):x:($muid):30000:Nix build user ($i):/var/empty:($dummy_shell)\n"
            }
            $mname
        })
        let member_list = ($members | str join ",")

        open --raw /etc/group
        | lines
        | where { not ($in | str starts-with "nixbld:") }
        | append $"nixbld:x:30000:($member_list)"
        | str join "\n"
        | $"($in)\n"
        | save --force /etc/group

        open --raw /etc/gshadow
        | lines
        | where { not ($in | str starts-with "nixbld:") }
        | append $"nixbld:!:($member_list):"
        | str join "\n"
        | $"($in)\n"
        | save --force /etc/gshadow

        if ("/nix/var/nix/db/db.sqlite" | path type) == "symlink" {
            let db_src = ("/nix/var/nix/db/db.sqlite" | path expand | path dirname)
            let tmp = (^mktemp -d | str trim)
            ^cp -r $"($db_src)/." $tmp
            for f in ["db.sqlite" "db.sqlite-shm" "db.sqlite-wal" "big-lock" "reserved" "schema"] {
                let p = $"/nix/var/nix/db/($f)"
                if ($p | path exists) { ^rm -f $p }
            }
            ^cp -r $"($tmp)/." /nix/var/nix/db/
            ^rm -rf $tmp
            ^chmod 644 /nix/var/nix/db/db.sqlite
            ^chmod 600 /nix/var/nix/db/big-lock
            ^chmod 600 /nix/var/nix/db/reserved
        }

        ##############################################################################
        # Arch config
        ##############################################################################
        let container_arch = (^uname -m | str trim)
        if $container_arch == "aarch64" {
            file-append /etc/nix/nix.conf "\nsystem = aarch64-linux\nextra-platforms = x86_64-linux\n"
            ${sandboxBlock}
        }
      ''
    else ''
      # Nix daemon disabled (${cfg.mode} mode)
    '';

  # ---------------------------------------------------------------------------
  # Phase 8: SFTP symlink
  # ---------------------------------------------------------------------------
  phaseSftpSymlink =
    if cfg.ssh != null then ''
      ##############################################################################
      # SFTP symlink
      ##############################################################################
      if ("${pkgs.openssh}/libexec/sftp-server" | path exists) {
          ^ln -sf "${pkgs.openssh}/libexec/sftp-server" /bin/sftp-server
          ^mkdir -p /run/current-system/sw/libexec
          ^ln -sf "${pkgs.openssh}/libexec/sftp-server" /run/current-system/sw/libexec/sftp-server
      }
    ''
    else "";

  # ---------------------------------------------------------------------------
  # Phase 9: Cargo cache
  # ---------------------------------------------------------------------------
  phaseCargoCache =
    if cfg.hasToolchain
    then ''
      ##############################################################################
      # Cargo target cache
      ##############################################################################
      let cargo_target = "/var/cache/cargo-target"
      ^mkdir -p $cargo_target
      ^chown -R $"($dev_user.uid):($dev_user.gid)" /var/cache
      ^chmod 0755 $cargo_target
      $env.CARGO_TARGET_DIR = $cargo_target
    ''
    else "";

  # ---------------------------------------------------------------------------
  # Phase 10: Banner
  # ---------------------------------------------------------------------------
  phaseBanner = ''
    ##############################################################################
    # Banner
    ##############################################################################
    if ("/etc/container-info" | path exists) {
        ^cat /etc/container-info
    }
    print $" • User ............. ($dev_user.user)  \(uid=($dev_user.uid) / gid=($dev_user.gid)\)"
    print $" • Mode ............. ${cfg.mode}"
    if ("/workspace" | path exists) {
        let is_mounted = (open --raw /proc/mounts | str contains " /workspace ")
        if $is_mounted {
            print " • Volume mount ..... /workspace is mounted"
        }
    }
    print " 🆘  Type 'container-help' for usage instructions"
    print "────────────────────────────────────────────────────────────────────────────"
  '';

  # ---------------------------------------------------------------------------
  # Phase 11: Vigil layer + launch
  #
  # CI/pipeline: vigild as PID 1, pipeline-runner supervised with passthrough logs
  # Dev/agent:   vigild backgrounded managing background services,
  #              shell exec'd as foreground with graceful degradation
  # ---------------------------------------------------------------------------

  # Nix daemon service — only when enabled, only for dev/agent
  nixDaemonServiceBlock =
    if cfg.nix.enableDaemon
    then ''

        nix-daemon:
          summary: Nix build daemon
          command: /bin/nix-daemon --daemon
          startup: enabled
          on-success: restart
          on-failure: restart
      ''
    else "";

  # Dropbear SSH service — only for dev/agent with SSH configured
  sshServiceBlock =
    if cfg.mode == "dev" || cfg.mode == "ai-agent" || cfg.mode == "infra-agent"
    then
      let port = toString cfg.ssh.port;
      in ''

        dropbear:
          summary: SSH server (Dropbear)
          command: >-
            dropbear -F -E -e -a -s
            -r /home/DEV_USER_PLACEHOLDER/.ssh/dropbear_rsa_host_key
            -r /home/DEV_USER_PLACEHOLDER/.ssh/dropbear_ed25519_host_key
            -p 0.0.0.0:${port}
          startup: disabled
          on-success: restart
          on-failure: restart
      ''
    else "";

  vigilLayer =
  if cfg.mode == "ci" then ''
    summary: CI pipeline runner

    services:

      pipeline-runner:
        summary: Pipeline runner
        command: ${nuBin} /etc/pipeline/pipeline_runner.nu
        startup: enabled
        logs-forward: passthrough
        environment:
          PIPELINE_TARGET: PIPELINE_TARGET_PLACEHOLDER
        on-success: success-shutdown
        on-failure: failure-shutdown
  ''
  else if cfg.mode == "dev" then ''
    summary: dev container background services
    ${nixDaemonServiceBlock}
    ${sshServiceBlock}
  ''
  else if cfg.mode == "infra-agent" then ''
    summary: infrastructure agent services

    services:

      agent-supervisor:
        summary: Agent supervisor
        command: /bin/agent-supervisor
        startup: enabled
        logs-forward: passthrough
        on-success: success-shutdown
        on-failure: failure-shutdown
    ${sshServiceBlock}
  ''
  else if cfg.mode == "ai-agent" then ''
    summary: AI agent background services

    services:

      agent-supervisor:
        summary: Agent supervisor
        command: /bin/agent-supervisor
        startup: enabled
        logs-forward: passthrough
        on-success: restart
        on-failure: restart
    ${sshServiceBlock}
  ''
  else throw "entrypoint: unknown mode '${cfg.mode}'";

  phaseVigilExec =
  if cfg.mode == "ci" || cfg.mode == "infra-agent" then ''
    ##############################################################################
    # CI/InfraAgent: vigild as PID 1
    ##############################################################################
    ^mkdir -p /run/vigil/layers

    let layer_yaml = "${vigilLayer}"
        | str replace --all "PIPELINE_TARGET_PLACEHOLDER" ($env.PIPELINE_STAGE? | default "all")

    $layer_yaml | save --force /run/vigil/layers/001-container.yaml

    exec /bin/vigild --layers-dir /run/vigil/layers --socket /run/vigil/vigild.sock
  ''
  else ''
    ##############################################################################
    # Dev/AIAgent: vigild backgrounded, shell exec'd as foreground
    ##############################################################################
    ^mkdir -p /run/vigil/layers

    let layer_yaml = "${vigilLayer}"
        | str replace --all "DEV_USER_PLACEHOLDER" $dev_user.user

    $layer_yaml | save --force /run/vigil/layers/001-container.yaml

    job spawn { ^/bin/vigild --layers-dir /run/vigil/layers --socket /run/vigil/vigild.sock }

    let vigild_ready = (
        1..20 | each { |_|
            ^sleep 0.1
            "/run/vigil/vigild.sock" | path exists
        } | any { |x| $x }
    )
    if not $vigild_ready {
        warn "vigild did not start within 2s — background services will not be supervised"
        warn "Container will still function — dropping to shell"
    }

    if $dev_user.user != "root" {
        $env.HOME    = $"/home/($dev_user.user)"
        $env.USER    = $dev_user.user
        $env.LOGNAME = $dev_user.user
        $env.SHELL   = "${shellBin}"
        $env.XDG_CACHE_HOME  = $"/home/($dev_user.user)/.cache"
        $env.XDG_CONFIG_HOME = $"/home/($dev_user.user)/.config"
        $env.XDG_DATA_HOME   = $"/home/($dev_user.user)/.local/share"
        exec chroot --userspec $"($dev_user.uid):($dev_user.gid)" / ${shellBin} -l
    } else {
        exec ${shellBin}
    }
  '';

in
  pkgs.writeTextFile {
    name        = "start.nu";
    destination = "/bin/start.nu";
    executable  = true;
    text        =
      phasePreamble
      + phaseStorePathExports
      + phaseUserCreation
      + phaseAiSetup
      + phaseSudo
      + phaseNixDaemon
      + phaseSftpSymlink
      + phaseCargoCache
      + phaseBanner
      + phaseVigilExec;
  }
