# polar-container-lib/nix/shell-dash.nix
#
# Minimal POSIX shell (dash) environment for minimal containers.
# Invoked by shell.nix when cfg.shell.type == "minimal-dash".
#
# Produces:
#   - /etc/profile          — minimal POSIX login profile
#   - /etc/shells           — registers /bin/sh as a valid shell
#
# Deliberately omits: color themes, plugins, atuin, starship, direnv,
# interactive completions, or any other ergonomic tooling.
# The goal is a clean POSIX baseline, nothing more.
#
# Note: dash is installed at /bin/dash and symlinked to /bin/sh via
# the shell packages in packages.nix. The /bin/sh symlink is set up
# by packages.nix via pkgs.dash which provides /bin/sh on NixOS.

{ pkgs
, cfg
}:

let
  # Minimal /etc/profile for POSIX sh
  # Sets PATH to include the Nix store bin locations and /bin.
  # Does NOT set up any interactive experience.
  profileText = ''
    # /etc/profile — minimal POSIX login profile
    # Generated by nix-container-lib (minimal-dash mode).

    # Basic PATH — Nix store paths are in PATH via the OCI config.Env,
    # but set a sensible fallback for scripts that reset PATH.
    export PATH=/bin:/usr/bin

    # SSL certificates
    export SSL_CERT_FILE=/etc/ssl/certs/ca-bundle.crt
    export SSL_CERT_DIR=/etc/ssl/certs

    # Source user profile if it exists
    if [ -f "$HOME/.profile" ]; then
      . "$HOME/.profile"
    fi
  '';

  shellsText = ''
    /bin/sh
    /bin/dash
  '';

  profile = pkgs.writeTextFile {
    name        = "profile";
    destination = "/etc/profile";
    text        = profileText;
  };

  etcShells = pkgs.writeTextFile {
    name        = "shells-dash";
    destination = "/etc/shells";
    text        = shellsText;
  };

in
  [ profile etcShells ]
