# polar-container-lib/nix/shell-nu-minimal.nix
#
# Minimal nushell environment for minimal containers.
# Invoked by shell.nix when cfg.shell.type == "minimal-nu".
#
# Produces:
#   - /etc/nushell/config.nu  — minimal system-wide nushell config
#   - /etc/nushell/env.nu     — minimal system-wide env setup
#   - /etc/shells             — registers /bin/nu as a valid shell
#
# Deliberately omits: color themes, plugins, atuin, starship, direnv,
# greeting, SSH management, or any other interactive ergonomics.
# The goal is a functional nushell baseline for scripting and light
# interactive use in minimal containers, not a full dev experience.
#
# Configuration decisions:
#   - vi mode (because emacs mode is never correct)
#   - show_banner: false (containers don't need a welcome screen)
#   - fuzzy completions (universally useful, zero cost)
#   - rounded table borders (readable, minimal)
#   - No color theme (let the terminal handle it)
#   - No tool integrations (atuin, starship, direnv belong in Interactive)

{ pkgs
, cfg
}:

let

  nuConfigText = ''
    # /etc/nushell/config.nu
    # Minimal nushell configuration — generated by nix-container-lib.
    # No plugins. No themes. No tool integrations.
    # Add customization in ~/.config/nushell/config.nu

    $env.config = {
      show_banner: false
      edit_mode: vi

      cursor_shape: {
        vi_insert: line
        vi_normal: block
        emacs:     line
      }

      completions: {
        case_sensitive: false
        quick:          true
        partial:        true
        algorithm:      "fuzzy"
        external: {
          enable:      true
          max_results: 50
        }
      }

      table: {
        mode:             rounded
        index_mode:       always
        show_empty:       true
        padding:          { left: 1, right: 1 }
        trim: {
          methodology:    wrapping
          wrapping_try_keep_words: true
          truncating_suffix: "..."
        }
      }

      history: {
        max_size:      10_000
        sync_on_enter: true
        file_format:   "sqlite"
        isolation:     false
      }

      error_style: "fancy"
    }
  '';

  nuEnvText = ''
    # /etc/nushell/env.nu
    # Minimal nushell environment setup — generated by nix-container-lib.

    # SSL certificates
    $env.SSL_CERT_FILE = "/etc/ssl/certs/ca-bundle.crt"
    $env.SSL_CERT_DIR  = "/etc/ssl/certs"

    # Shell identity
    $env.SHELL = "${pkgs.nushell}/bin/nu"
  '';

  shellsText = ''
    /bin/nu
    /bin/nushell
  '';

  nuConfig = pkgs.writeTextFile {
    name        = "nu-minimal-config";
    destination = "/etc/nushell/config.nu";
    text        = nuConfigText;
  };

  nuEnv = pkgs.writeTextFile {
    name        = "nu-minimal-env";
    destination = "/etc/nushell/env.nu";
    text        = nuEnvText;
  };

  etcShells = pkgs.writeTextFile {
    name        = "shells-nu-minimal";
    destination = "/etc/shells";
    text        = shellsText;
  };

in
  [ nuConfig nuEnv etcShells ]
